export class Registro {
    constructor(

        public idRegistro: number,
        public clvRegistro: string,
        public numeroFolio: string,
        public fecha: string,
        public clvCliente: string,
        public nombrePaciente: string,
        public genero: string,
        public edad: number,
        public procedencia: string,
        public destino: string,
        public solicito: string,
        public clvServicio: string,
        public poliza: string,
        public siniestro: string,
        public inciso: string,
        public reporte: string,
        public autorizacion: string,
        public clvEmpleados: string,
        public estado: string,
        public ultimaActualizacion: string,
        public observacion: string,
        public ocupacion: string,
        public telefono: string,
        public odometro: string,
        public llamada: string,
        public ambulancia: string,
        public rt: string,
        public folioPm: string,
        public personal: string,
        public clvMembresia: string,
        public diagnostico: string,
        public categoria: string,
        public folioFactura: string,
        public costo: string,
        public activo: boolean,
        public fechaCreacion: string

    ) { }
}
